# Generated by Django 4.1.7 on 2023-04-24 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dorm', '0005_alter_room_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='user',
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
    ]
